eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    metadata-map:
      management.port: ${management.port:8081}
server:
  port: 8030
  
info:
  component: Turbine

turbine:
  clusterNameExpression: new String("default")
  appConfig: lab-6-sentence,lab-6-subject,lab-6-verb,lab-6-article,lab-6-adjective,lab-6-noun

management:
  port: 8990